---
title: "Data ready for presentation 10/14"
author: "Group 3"
date: "`r Sys.Date()`"
output: 
  html_notebook:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
---

## Cliamte Data

In this section we display the climate data we currently have. The CO2 and AQI represents the mean value of the corresponding day, ranging from 2024/01/01 to 2025/3/29. For the data processing part and the specific location of the station, please see the data processing file for climate data.

```{r Importing data, include = FALSE} 
library(sf)
library(tmap)
library(dplyr)
library(tidyr)
library(arrow)
library(ggplot2)

# Reading Data
climate = read.csv("processed_pm2.5_AQI.csv") %>% 
  select(c(-X)) %>%
  mutate(Date = as.Date(Date, format = "%m/%d/%Y"))
```

```{r}
# Summary Statistics
climate %>%
  summary()
```

# Plot for PM2.5

```{r}
ggplot(climate, aes(x = Date, y = PM2.5)) +
  geom_line(color = "darkblue", width = 1.5) +
  labs(
    title = "PM2.5 Levels at East Village, Manhattan Over Time",
    x = "Date",
    y = "PM2.5 (µg/m³)"
  ) +
  theme_minimal(base_size = 14)
```

# Plot for AQI

```{r}
ggplot(climate, aes(x = Date, y = AQI)) +
  geom_line(color = "darkgreen", width = 1.5) +
  labs(
    title = "AQI at East Village, Manhattan Over Time",
    x = "Date",
    y = "AQI"
  ) +
  theme_minimal(base_size = 14)
```