---
title: "Climate Data Processing"
author: "Yao, Ju-Chien b12303125"
date: "`r Sys.Date()`"
output: 
  html_notebook:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
---

## Setting up

```{r Importing data, include = FALSE} 
library(sf)
library(tmap)
library(dplyr)
library(tidyr)
library(arrow)

# Reading Data
nyc_shp = st_read("C:/114-1_Autumn/Data_science_and_social_inquiry/data/nyc_map/taxi_zones.shp")
ny_air = read.csv("C:/114-1_Autumn/Data_science_and_social_inquiry/data/air_quality/ad_viz_plotval_data.csv")
```

```{r, eval=FALSE}
pre_fhv = read_parquet("C:/114-1_Autumn/Data_science_and_social_inquiry/data/nyc_july2024/fhv_tripdata_2024-07.parquet")

pre_green = read_parquet("C:/114-1_Autumn/Data_science_and_social_inquiry/data/nyc_july2024/green_tripdata_2024-07.parquet")

pre_yellow = read_parquet("C:/114-1_Autumn/Data_science_and_social_inquiry/data/nyc_july2024/yellow_tripdata_2024-07.parquet")

pre_fhvhv = read_parquet("C:/114-1_Autumn/Data_science_and_social_inquiry/data/nyc_july2024/fhvhv_tripdata_2024-07.parquet")

post_fhv = read_parquet("C:/114-1_Autumn/Data_science_and_social_inquiry/data/nyc_july2025/fhv_tripdata_2025-07.parquet")

post_yellow = read_parquet("C:/114-1_Autumn/Data_science_and_social_inquiry/data/nyc_july2025/yellow_tripdata_2025-07.parquet")

post_green = read_parquet("C:/114-1_Autumn/Data_science_and_social_inquiry/data/nyc_july2025/green_tripdata_2025-07.parquet")

post_fhvhv = read_parquet("C:/114-1_Autumn/Data_science_and_social_inquiry/data/nyc_july2025/fhvhv_tripdata_2025-07.parquet")
```

# Showing Manhattan shp

```{r}
# Selecting Manhattan
mht_shp = nyc_shp %>%
  filter(borough == "Manhattan")

tm_shape(mht_shp) +
  tm_polygons()
```

# Transforming the crs and plotting

```{r}
ny_air_sf <- ny_air %>%
  filter(!is.na(Site.Latitude) & !is.na(Site.Longitude)) %>%
  st_as_sf(coords = c("Site.Longitude", "Site.Latitude"), crs = 4326)

# Adjust the coordinate of shp
mht_shp = st_transform(mht_shp, st_crs(ny_air_sf))
st_crs(mht_shp)

# 使用 tmap 繪圖
tm_shape(mht_shp) +
  tm_polygons(col = "lightgray", border.col = "black") +  # 底圖 polygon
tm_shape(ny_air_sf) +
  tm_dots(size = 0.5, fill = "red") +                     # 測站點
  tm_layout(title = "Manhattan Air Quality / Weather Stations", frame = TRUE)
```

# Selecting stations inside Manhattan

```{r}
sites_in_mht = st_intersection(ny_air_sf, mht_shp) 

tm_shape(mht_shp) +
  tm_polygons(col = "lightgray", border.col = "black") +  # 底圖 polygon
tm_shape(sites_in_mht) +
  tm_dots(size = 0.5, fill = "red") +                     # 測站點
  tm_layout(title = "Manhattan Air Quality / Weather Stations", frame = TRUE)
```

# Selecting the station "under" 61st street

```{r}
unique(sites_in_mht$zone)
```

"East Village" is the only station in the area under regulation, we extract the data of the site specifically. The data cleaning result would be shown in another file (name).

```{r}
evile_df_2025 = sites_in_mht %>%
  filter(zone == "East Village") %>%
  as.data.frame() %>%
  rename(
    "PM2.5"= Daily.Mean.PM2.5.Concentration,
    "AQI" = Daily.AQI.Value) %>%
  select(Date, PM2.5, AQI)
```

```{r}
evile_df_2024 = read.csv("C:/114-1_Autumn/Data_science_and_social_inquiry/data/air_quality/2024-pm2.5.csv") %>%
  rename(
    "PM2.5"= Daily.Mean.PM2.5.Concentration,
    "AQI" = Daily.AQI.Value) %>%
  select(Date, PM2.5, AQI)

evile_df = rbind(evile_df_2024, evile_df_2025)
write.csv(evile_df, file = "C:/114-1_Autumn/Data_science_and_social_inquiry/data/air_quality/processed_pm2.5_AQI.csv")
```